name: CI
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["*"]

jobs:
  build:
    name: CI
    strategy:
      fail-fast: false
      matrix: 
        os: [macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4

      - name: Cache SBT
        uses: actions/cache@v3
        with:
          path: |
            ~/.ivy2/cache
            ~/.sbt
          key: ${{ runner.os }}-sbt-${{ hashFiles('**/*.sbt') }}

      - name: Cache sbt-vcpkg
        uses: actions/cache@v3
        with:
          path: |
            ~/Library/Caches/sbt-vcpkg
          key: ${{ runner.os }}-sbt-vcpkg


      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin' 
          java-version: 17

      - uses: sbt/setup-sbt@v1

      - name: Setup
        run: |
          PLATFORM="$(uname)"

          if [ $PLATFORM == "Darwin" ]; then
            echo "It's a Mac"
            brew install llvm@14
          else
            echo "It's a Linux"
            wget https://apt.llvm.org/llvm.sh
            chmod +x llvm.sh
            sudo ./llvm.sh 14
          fi

      - name: Compile examples
        run: sbt parts/nativeLink

  mergify-build-checkpoint:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: I only exist to please Mergify :(
        run: echo "It's a sad existence but necessary"
