name: CI
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["*"]

jobs:
  build:
    name: CI
    strategy:
      fail-fast: false
      matrix: 
        os: [macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-java@v2
        with:
          distribution: 'temurin' 
          java-version: 17

      - name: Setup
        run: |
          PLATFORM="$(uname)"

          if [ $PLATFORM == "Darwin" ]; then
            echo "It's a Mac"
            brew install llvm
          else
            echo "It's a Linux"
            sudo apt update
            sudo apt install lsb-release wget software-properties-common
            wget -O - https://apt.llvm.org/llvm-snapshot.gpg.key | sudo apt-key add -
            sudo add-apt-repository "deb http://apt.llvm.org/focal/     llvm-toolchain-focal-13   main"
            sudo apt-get update 
            sudo apt-get install clang-13 lldb-13 libclang-13-dev llvm-13-dev
          fi

      - name: Compile examples
        run: sbt parts/nativeLink

      - name: Cache SBT
        uses: actions/cache@v3
        with:
          path: |
            ~/.ivy2/cache
            ~/.sbt
          key: ${{ runner.os }}-sbt-${{ hashFiles('**/*.sbt') }}

      - name: Cache sbt-vcpkg
        uses: actions/cache@v3
        with:
          path: |
            ~/Library/Caches/sbt-vcpkg
          key: ${{ runner.os }}-sbt-vcpkg-${{ hashFiles('**/build.sbt') }}

